In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

# charger le fichier excel

In [10]:
from pathlib import Path
import pandas as pd

# Chemin absolu vers le dossier raw
RAW_FOLDER = Path.cwd().parent / "data" / "raw"

# Recherche automatique des fichiers Excel
fichiers_excel = list(RAW_FOLDER.glob("*.xlsx"))

print("Dossier recherché :", RAW_FOLDER)
print("Fichiers trouvés :", fichiers_excel)

Dossier recherché : c:\Users\fayel\OneDrive\github\data\data-analyse-clients-banque\data\raw
Fichiers trouvés : [WindowsPath('c:/Users/fayel/OneDrive/github/data/data-analyse-clients-banque/data/raw/Données_Primero_Bank.xlsx')]

In [11]:
if not fichiers_excel:
    raise FileNotFoundError("Aucun fichier Excel trouvé dans data/raw")

DATA_PATH = fichiers_excel[0]

print("Fichier utilisé :", DATA_PATH)
print("Existe réellement :", DATA_PATH.exists())

df = pd.read_excel(DATA_PATH, engine="openpyxl")

df.head()

Fichier utilisé : c:\Users\fayel\OneDrive\github\data\data-analyse-clients-banque\data\raw\Données_Primero_Bank.xlsx
Existe réellement : True

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,N° du client,Statut du client,Âge du client,Genre du client,Nb de personnes à charge,Niveau de diplôme,Statut marital,Catégorie du revenu annuel,Type de carte,Durée d'engagement en mois,Nb de mois inactif,Nb d'interactions,Montant crédit renouvellé,Nb de transactions,Utilisation moyenne de la carte
1,768805383,Client actuel,45,M,3,Lycée (équivalent baccalauréat),Marié(e),$60K - $80K,Blue,39,1,3,777,42,0.061
2,818770008,Client actuel,49,F,5,Licence,Célibataire,Moins de $40K,Blue,44,1,2,864,33,0.105
3,713982108,Client actuel,51,M,3,Licence,Marié(e),$80K - $120K,Blue,36,1,0,0,20,0
4,769911858,Client actuel,40,F,4,Lycée (équivalent baccalauréat),Non connu,Moins de $40K,Blue,34,4,1,2517,20,0.76

In [12]:
df = pd.read_excel(
    DATA_PATH,
    header=1,
    engine="openpyxl"
)

df.head()

,N° du client,Statut du client,Âge du client,Genre du client,Nb de personnes à charge,Niveau de diplôme,Statut marital,Catégorie du revenu annuel,Type de carte,Durée d'engagement en mois,Nb de mois inactif,Nb d'interactions,Montant crédit renouvellé,Nb de transactions,Utilisation moyenne de la carte
0,768805383,Client actuel,45,M,3,Lycée (équivalent baccalauréat),Marié(e),$60K - $80K,Blue,39,1,3,777,42,0.061
1,818770008,Client actuel,49,F,5,Licence,Célibataire,Moins de $40K,Blue,44,1,2,864,33,0.105
2,713982108,Client actuel,51,M,3,Licence,Marié(e),$80K - $120K,Blue,36,1,0,0,20,0.000
3,769911858,Client actuel,40,F,4,Lycée (équivalent baccalauréat),Non connu,Moins de $40K,Blue,34,4,1,2517,20,0.760
4,709106358,Client actuel,40,M,3,Sans diplôme,Marié(e),$60K - $80K,Blue,21,1,0,0,28,0.000

# Verifions la taille

In [13]:
print(f"Nombre de lignes : {df.shape[0]}")
print(f"Nombre de colonnes : {df.shape[1]}")

Nombre de lignes : 10127
Nombre de colonnes : 15

# Voir les noms de colonnes et les types de données

In [15]:
df.columns.to_list()

['N° du client',
 'Statut du client',
 'Âge du client',
 'Genre du client',
 'Nb de personnes à charge',
 'Niveau de diplôme',
 'Statut marital',
 'Catégorie du revenu annuel',
 'Type de carte',
 "Durée d'engagement en mois",
 'Nb de mois inactif',
 "Nb d'interactions",
 'Montant crédit renouvellé',
 'Nb de transactions',
 'Utilisation moyenne de la carte']

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 15 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   N° du client                     10127 non-null  int64
 1   Statut du client                 10127 non-null  str
 2   Âge du client                    10127 non-null  int64
 3   Genre du client                  10127 non-null  str
 4   Nb de personnes à charge         10127 non-null  int64
 5   Niveau de diplôme                10127 non-null  str
 6   Statut marital                   10127 non-null  str
 7   Catégorie du revenu annuel       10127 non-null  str
 8   Type de carte                    10127 non-null  str
 9   Durée d'engagement en mois       10127 non-null  int64
 10  Nb de mois inactif               10127 non-null  int64
 11  Nb d'interactions                10127 non-null  int64
 12  Montant crédit renouvellé        10127 non-null  int64
 13  Nb de transactions               10127 non-null  int64
 14  Utilisation moyenne de la carte  10127 non-null  float64
dtypes: float64(1), int64(8), str(6)
memory usage: 1.2 MB

# Recherche de Valeurs manquantes :

In [17]:
valeurs_manquantes = df.isna().sum()

valeurs_manquantes

N° du client                       0
Statut du client                   0
Âge du client                      0
Genre du client                    0
Nb de personnes à charge           0
Niveau de diplôme                  0
Statut marital                     0
Catégorie du revenu annuel         0
Type de carte                      0
Durée d'engagement en mois         0
Nb de mois inactif                 0
Nb d'interactions                  0
Montant crédit renouvellé          0
Nb de transactions                 0
Utilisation moyenne de la carte    0
dtype: int64

# Verifions les doublons

In [20]:
nombre_doublons = df.duplicated().sum()

print("Nombre de lignes dupliquées :", nombre_doublons)

Nombre de lignes dupliquées : 0

# Examinons la variable principale

In [21]:
df["Statut du client"].value_counts(dropna=False)

Statut du client
Client actuel    8491
Client perdu     1636
Name: count, dtype: int64

In [22]:
df["Statut du client"].value_counts(
    normalize=True,
    dropna=False
).mul(100).round(2)

Statut du client
Client actuel    83.85
Client perdu     16.15
Name: proportion, dtype: float64

# Statistiques generales

In [23]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
N° du client,10127.0,NaN,NaN,NaN,739177606.333663,36903783.450231,708082083.0,713036770.5,717926358.0,773143533.0,828343083.0
Statut du client,10127,2,Client actuel,8491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Âge du client,10127.0,NaN,NaN,NaN,46.334847,8.022482,26.0,41.0,46.0,52.0,73.0
Genre du client,10127,2,F,5358,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nb de personnes à charge,10127.0,NaN,NaN,NaN,2.346203,1.298908,0.0,1.0,2.0,3.0,5.0
Niveau de diplôme,10127,7,Licence,3128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Statut marital,10127,4,Marié(e),4547,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Catégorie du revenu annuel,10127,6,Moins de $40K,3183,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type de carte,10127,4,Blue,9436,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Durée d'engagement en mois,10127.0,NaN,NaN,NaN,35.928409,7.986416,13.0,31.0,36.0,40.0,56.0
Nb de mois inactif,10127.0,NaN,NaN,NaN,2.428854,1.19369,0.0,2.0,2.0,3.0,8.0
Nb d'interactions,10127.0,NaN,NaN,NaN,2.538067,1.323046,0.0,2.0,2.0,3.0,9.0
Montant crédit renouvellé,10127.0,NaN,NaN,NaN,1162.814061,814.987335,0.0,359.0,1276.0,1784.0,2517.0
Nb de transactions,10127.0,NaN,NaN,NaN,64.858695,23.47257,10.0,45.0,67.0,81.0,139.0
Utilisation moyenne de la carte,10127.0,NaN,NaN,NaN,0.274894,0.275691,0.0,0.023,0.176,0.503,0.999

# Examinons les catégories de chaque colonne

In [24]:
colonnes_categorielles = df.select_dtypes(include="object").columns

for colonne in colonnes_categorielles:
    print(f"\n--- {colonne} ---")
    print(df[colonne].value_counts(dropna=False))

--- Statut du client ---
Statut du client
Client actuel    8491
Client perdu     1636
Name: count, dtype: int64

--- Genre du client ---
Genre du client
F    5358
M    4769
Name: count, dtype: int64

--- Niveau de diplôme ---
Niveau de diplôme
Licence                            3128
Lycée (équivalent baccalauréat)    2013
Non connu                          1519
Sans diplôme                       1487
Niveau Bac+2                       1013
Master                              516
Doctorat                            451
Name: count, dtype: int64

--- Statut marital ---
Statut marital
Marié(e)       4547
Célibataire    4083
Non connu       749
Divorcé(e)      748
Name: count, dtype: int64

--- Catégorie du revenu annuel ---
Catégorie du revenu annuel
Moins de $40K    3183
$40K - $60K      1961
$60K - $80K      1577
$80K - $120K     1569
Non connu        1110
$120K +           727
Name: count, dtype: int64

--- Type de carte ---
Type de carte
Blue        9436
Silver       555
Gold         116
Platinum      20
Name: count, dtype: int64

C:\Users\fayel\AppData\Local\Temp\ipykernel_10712\2634987371.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  colonnes_categorielles = df.select_dtypes(include="object").columns

# Verifions les colonnes minimales et maximales

In [26]:
colonnes_numeriques = (
    df.select_dtypes(include="number")
    .columns
    .drop("N° du client")
)

df[colonnes_numeriques].agg(
    ["min", "max", "mean", "median"]
).T

                                  min       max         mean    median
Âge du client                    26.0    73.000    46.334847    46.000
Nb de personnes à charge          0.0     5.000     2.346203     2.000
Durée d'engagement en mois       13.0    56.000    35.928409    36.000
Nb de mois inactif                0.0     8.000     2.428854     2.000
Nb d'interactions                 0.0     9.000     2.538067     2.000
Montant crédit renouvellé         0.0  2517.000  1162.814061  1276.000
Nb de transactions               10.0   139.000    64.858695    67.000
Utilisation moyenne de la carte   0.0     0.999     0.274894     0.176

# Verifions les espaces cachées

In [29]:
for colonne in colonnes_categorielles:
    valeurs_avec_espaces = (
        df[colonne]
        .dropna()
        .astype(str)
        .loc[lambda x: x != x.str.strip()]
    )

    print(
        f"{colonne} : "
        f"{len(valeurs_avec_espaces)} valeur(s) avec espaces inutiles"
    )

Statut du client : 0 valeur(s) avec espaces inutiles
Genre du client : 0 valeur(s) avec espaces inutiles
Niveau de diplôme : 0 valeur(s) avec espaces inutiles
Statut marital : 0 valeur(s) avec espaces inutiles
Catégorie du revenu annuel : 0 valeur(s) avec espaces inutiles
Type de carte : 0 valeur(s) avec espaces inutiles

# Creer un resumé automatique de la qualité

In [30]:
resume_qualite = pd.DataFrame({
    "type": df.dtypes.astype(str),
    "valeurs_manquantes": df.isna().sum(),
    "pourcentage_manquant": df.isna().mean().mul(100).round(2),
    "valeurs_uniques": df.nunique(dropna=False)
})

resume_qualite

,type,valeurs_manquantes,pourcentage_manquant,valeurs_uniques
N° du client,int64,0,0.0,10127
Statut du client,str,0,0.0,2
Âge du client,int64,0,0.0,45
Genre du client,str,0,0.0,2
Nb de personnes à charge,int64,0,0.0,6
Niveau de diplôme,str,0,0.0,7
Statut marital,str,0,0.0,4
Catégorie du revenu annuel,str,0,0.0,6
Type de carte,str,0,0.0,4
Durée d'engagement en mois,int64,0,0.0,44
Nb de mois inactif,int64,0,0.0,9
Nb d'interactions,int64,0,0.0,10
Montant crédit renouvellé,int64,0,0.0,1974
Nb de transactions,int64,0,0.0,126
Utilisation moyenne de la carte,float64,0,0.0,964

# Conclusion



L’exploration initiale a permis de vérifier :

- les dimensions du jeu de données ;
- les noms et les types des variables ;
- la présence éventuelle de valeurs manquantes ;
- la présence de doublons ;
- l’unicité des identifiants clients ;
- la cohérence des catégories ;
- les plages de valeurs des variables numériques.

Les anomalies identifiées seront corrigées dans le notebook
`02_nettoyage_donnees.ipynb`.

- Nombre de clients : 10128
- Nombre de variables : 15
- Valeurs manquantes : 0
- Doublons complets : 0
- Identifiants dupliqués : 0
- Anomalies de catégories : 0